- name: build
  type: eureka/kaniko:v2
  env:
    DOCKERFILE: .ci/test/Dockerfile
    CONTEXT: ./tests
    IMAGE_NAME: kaniko  # final actual name: harbor.eurekacloud.io/eureka/kaniko:v2
    IMAGE_TAG: v2 # If you not enter, its value would be $GIT_COMMIT
    HELM_VALUES_FILE: charts/values.yaml   
      # 会自动注册值  {{ .Values.images.$IMAGE_NAME }}  .Values.eureka.envs.DOCKER_REGISTRY
      # 后面的contain可以使用 image: {{ index .Values "images" "hello-ingress" }}  todo 这个值有点奇怪

    