// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/Knowckx/Asuka/curdinfm/pb/newobj.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	github.com/Knowckx/Asuka/curdinfm/pb/newobj.proto

It has these top-level messages:
	NewObjMod
	NewObjMods
	Language
	RankIndexWithLang
	EmptyMessage
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 枚举
type LanguageType int32

const (
	LanguageType_zh_CN LanguageType = 0
	LanguageType_zh_HK LanguageType = 1
	LanguageType_en_US LanguageType = 2
)

var LanguageType_name = map[int32]string{
	0: "zh_CN",
	1: "zh_HK",
	2: "en_US",
}
var LanguageType_value = map[string]int32{
	"zh_CN": 0,
	"zh_HK": 1,
	"en_US": 2,
}

func (x LanguageType) String() string {
	return proto.EnumName(LanguageType_name, int32(x))
}
func (LanguageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 新的物体
type NewObjMod struct {
	RankIndex int32        `protobuf:"varint,1,opt,name=RankIndex" json:"RankIndex,omitempty"`
	Lang      LanguageType `protobuf:"varint,2,opt,name=Lang,enum=pb.LanguageType" json:"Lang,omitempty"`
	RankName  string       `protobuf:"bytes,3,opt,name=RankName" json:"RankName,omitempty"`
}

func (m *NewObjMod) Reset()                    { *m = NewObjMod{} }
func (m *NewObjMod) String() string            { return proto.CompactTextString(m) }
func (*NewObjMod) ProtoMessage()               {}
func (*NewObjMod) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NewObjMod) GetRankIndex() int32 {
	if m != nil {
		return m.RankIndex
	}
	return 0
}

func (m *NewObjMod) GetLang() LanguageType {
	if m != nil {
		return m.Lang
	}
	return LanguageType_zh_CN
}

func (m *NewObjMod) GetRankName() string {
	if m != nil {
		return m.RankName
	}
	return ""
}

// 很多物体们
type NewObjMods struct {
	Mods []*NewObjMod `protobuf:"bytes,1,rep,name=Mods" json:"Mods,omitempty"`
}

func (m *NewObjMods) Reset()                    { *m = NewObjMods{} }
func (m *NewObjMods) String() string            { return proto.CompactTextString(m) }
func (*NewObjMods) ProtoMessage()               {}
func (*NewObjMods) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NewObjMods) GetMods() []*NewObjMod {
	if m != nil {
		return m.Mods
	}
	return nil
}

type Language struct {
	Lang LanguageType `protobuf:"varint,1,opt,name=Lang,enum=pb.LanguageType" json:"Lang,omitempty"`
}

func (m *Language) Reset()                    { *m = Language{} }
func (m *Language) String() string            { return proto.CompactTextString(m) }
func (*Language) ProtoMessage()               {}
func (*Language) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Language) GetLang() LanguageType {
	if m != nil {
		return m.Lang
	}
	return LanguageType_zh_CN
}

type RankIndexWithLang struct {
	RankIndex int32        `protobuf:"varint,1,opt,name=RankIndex" json:"RankIndex,omitempty"`
	Lang      LanguageType `protobuf:"varint,2,opt,name=Lang,enum=pb.LanguageType" json:"Lang,omitempty"`
}

func (m *RankIndexWithLang) Reset()                    { *m = RankIndexWithLang{} }
func (m *RankIndexWithLang) String() string            { return proto.CompactTextString(m) }
func (*RankIndexWithLang) ProtoMessage()               {}
func (*RankIndexWithLang) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RankIndexWithLang) GetRankIndex() int32 {
	if m != nil {
		return m.RankIndex
	}
	return 0
}

func (m *RankIndexWithLang) GetLang() LanguageType {
	if m != nil {
		return m.Lang
	}
	return LanguageType_zh_CN
}

// 为了测试
type EmptyMessage struct {
}

func (m *EmptyMessage) Reset()                    { *m = EmptyMessage{} }
func (m *EmptyMessage) String() string            { return proto.CompactTextString(m) }
func (*EmptyMessage) ProtoMessage()               {}
func (*EmptyMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*NewObjMod)(nil), "pb.NewObjMod")
	proto.RegisterType((*NewObjMods)(nil), "pb.NewObjMods")
	proto.RegisterType((*Language)(nil), "pb.Language")
	proto.RegisterType((*RankIndexWithLang)(nil), "pb.RankIndexWithLang")
	proto.RegisterType((*EmptyMessage)(nil), "pb.EmptyMessage")
	proto.RegisterEnum("pb.LanguageType", LanguageType_name, LanguageType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for XXXXSrv service

type XXXXSrvClient interface {
	// ----------------- 排行榜配置外语翻译文本 start -----------------
	// OA 增加 榜单配置对应的外语文本
	AddNewObjMod(ctx context.Context, in *NewObjMod, opts ...client.CallOption) (*EmptyMessage, error)
	// OA 删除 某个榜单的外语文本
	DelNewObjMod(ctx context.Context, in *RankIndexWithLang, opts ...client.CallOption) (*EmptyMessage, error)
	// OA 查询 某个榜单全部的外语文本
	GetNewObjMods(ctx context.Context, in *RankIndexWithLang, opts ...client.CallOption) (*NewObjMods, error)
	// OA 修改 榜单配置对应的外语文本
	UpdateNewObjMod(ctx context.Context, in *NewObjMod, opts ...client.CallOption) (*EmptyMessage, error)
}

type xXXXSrvClient struct {
	c           client.Client
	serviceName string
}

func NewXXXXSrvClient(serviceName string, c client.Client) XXXXSrvClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "pb"
	}
	return &xXXXSrvClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *xXXXSrvClient) AddNewObjMod(ctx context.Context, in *NewObjMod, opts ...client.CallOption) (*EmptyMessage, error) {
	req := c.c.NewRequest(c.serviceName, "XXXXSrv.AddNewObjMod", in)
	out := new(EmptyMessage)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xXXXSrvClient) DelNewObjMod(ctx context.Context, in *RankIndexWithLang, opts ...client.CallOption) (*EmptyMessage, error) {
	req := c.c.NewRequest(c.serviceName, "XXXXSrv.DelNewObjMod", in)
	out := new(EmptyMessage)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xXXXSrvClient) GetNewObjMods(ctx context.Context, in *RankIndexWithLang, opts ...client.CallOption) (*NewObjMods, error) {
	req := c.c.NewRequest(c.serviceName, "XXXXSrv.GetNewObjMods", in)
	out := new(NewObjMods)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xXXXSrvClient) UpdateNewObjMod(ctx context.Context, in *NewObjMod, opts ...client.CallOption) (*EmptyMessage, error) {
	req := c.c.NewRequest(c.serviceName, "XXXXSrv.UpdateNewObjMod", in)
	out := new(EmptyMessage)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for XXXXSrv service

type XXXXSrvHandler interface {
	// ----------------- 排行榜配置外语翻译文本 start -----------------
	// OA 增加 榜单配置对应的外语文本
	AddNewObjMod(context.Context, *NewObjMod, *EmptyMessage) error
	// OA 删除 某个榜单的外语文本
	DelNewObjMod(context.Context, *RankIndexWithLang, *EmptyMessage) error
	// OA 查询 某个榜单全部的外语文本
	GetNewObjMods(context.Context, *RankIndexWithLang, *NewObjMods) error
	// OA 修改 榜单配置对应的外语文本
	UpdateNewObjMod(context.Context, *NewObjMod, *EmptyMessage) error
}

func RegisterXXXXSrvHandler(s server.Server, hdlr XXXXSrvHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&XXXXSrv{hdlr}, opts...))
}

type XXXXSrv struct {
	XXXXSrvHandler
}

func (h *XXXXSrv) AddNewObjMod(ctx context.Context, in *NewObjMod, out *EmptyMessage) error {
	return h.XXXXSrvHandler.AddNewObjMod(ctx, in, out)
}

func (h *XXXXSrv) DelNewObjMod(ctx context.Context, in *RankIndexWithLang, out *EmptyMessage) error {
	return h.XXXXSrvHandler.DelNewObjMod(ctx, in, out)
}

func (h *XXXXSrv) GetNewObjMods(ctx context.Context, in *RankIndexWithLang, out *NewObjMods) error {
	return h.XXXXSrvHandler.GetNewObjMods(ctx, in, out)
}

func (h *XXXXSrv) UpdateNewObjMod(ctx context.Context, in *NewObjMod, out *EmptyMessage) error {
	return h.XXXXSrvHandler.UpdateNewObjMod(ctx, in, out)
}

func init() { proto.RegisterFile("github.com/Knowckx/Asuka/curdinfm/pb/newobj.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0x4d, 0x4f, 0xea, 0x40,
	0x14, 0x65, 0xf8, 0x78, 0x8f, 0xde, 0x57, 0x78, 0x75, 0x12, 0x93, 0x86, 0xb8, 0xa8, 0x8d, 0x8b,
	0xc6, 0x45, 0x2b, 0xe8, 0x42, 0x97, 0x44, 0x8d, 0x1a, 0x04, 0x93, 0x22, 0xa1, 0x3b, 0x32, 0x43,
	0xc7, 0x02, 0xb5, 0xd3, 0x09, 0x6d, 0x05, 0xfc, 0xc3, 0xfe, 0x0d, 0xd3, 0x46, 0x0b, 0xc4, 0x8f,
	0xc4, 0xc4, 0xd5, 0xdc, 0x3b, 0xe7, 0x9e, 0x39, 0xe7, 0xdc, 0x0c, 0x34, 0xbd, 0x69, 0x3c, 0x49,
	0xa8, 0x39, 0x0e, 0x03, 0xab, 0xc3, 0xc3, 0xc5, 0xd8, 0x5f, 0x5a, 0xed, 0x28, 0xf1, 0x89, 0x35,
	0x4e, 0xe6, 0xee, 0x94, 0x3f, 0x04, 0x96, 0xa0, 0x16, 0x67, 0x8b, 0x90, 0xce, 0x4c, 0x31, 0x0f,
	0xe3, 0x10, 0x17, 0x05, 0xd5, 0x7d, 0x90, 0x7a, 0x6c, 0x71, 0x47, 0x67, 0xdd, 0xd0, 0xc5, 0x7b,
	0x20, 0xd9, 0x84, 0xfb, 0x37, 0xdc, 0x65, 0x4b, 0x15, 0x69, 0xc8, 0xa8, 0xd8, 0xeb, 0x0b, 0x7c,
	0x00, 0xe5, 0x5b, 0xc2, 0x3d, 0xb5, 0xa8, 0x21, 0xa3, 0xde, 0x52, 0x4c, 0x41, 0xcd, 0xb4, 0x4f,
	0x88, 0xc7, 0xee, 0x57, 0x82, 0xd9, 0x19, 0x8a, 0x1b, 0x50, 0x4d, 0x29, 0x3d, 0x12, 0x30, 0xb5,
	0xa4, 0x21, 0x43, 0xb2, 0xf3, 0x5e, 0xb7, 0x00, 0x72, 0xb1, 0x08, 0xef, 0x43, 0x39, 0x3d, 0x55,
	0xa4, 0x95, 0x8c, 0x7f, 0xad, 0x5a, 0xfa, 0x5e, 0x8e, 0xda, 0x19, 0xa4, 0x1f, 0x41, 0xf5, 0x5d,
	0x22, 0x97, 0x47, 0xdf, 0xc9, 0xeb, 0x43, 0xd8, 0xc9, 0x1d, 0x0f, 0xa7, 0xf1, 0x24, 0xf3, 0xf4,
	0x0b, 0xb9, 0xf4, 0x3a, 0xc8, 0x97, 0x81, 0x88, 0x57, 0x5d, 0x16, 0x45, 0xc4, 0x63, 0x87, 0x16,
	0xc8, 0x9b, 0x53, 0x58, 0x82, 0xca, 0xf3, 0x64, 0x74, 0xde, 0x53, 0x0a, 0x6f, 0xe5, 0x75, 0x47,
	0x41, 0x69, 0xc9, 0xf8, 0x68, 0xd0, 0x57, 0x8a, 0xad, 0x17, 0x04, 0x7f, 0x1d, 0xc7, 0x71, 0xfa,
	0xf3, 0x27, 0xdc, 0x04, 0xb9, 0xed, 0xba, 0xeb, 0xc5, 0x6f, 0x87, 0x6f, 0x64, 0x1e, 0x36, 0xd5,
	0xf4, 0x02, 0x3e, 0x03, 0xf9, 0x82, 0x3d, 0xae, 0x29, 0xbb, 0xe9, 0xcc, 0x87, 0xa8, 0x9f, 0x52,
	0x4f, 0xa1, 0x76, 0xc5, 0xe2, 0x8d, 0xcd, 0x7f, 0xc1, 0xad, 0x6f, 0xb9, 0x88, 0xf4, 0x02, 0x3e,
	0x81, 0xff, 0x03, 0xe1, 0x92, 0x98, 0xfd, 0xc4, 0x2a, 0xfd, 0x93, 0x7d, 0xaf, 0xe3, 0xd7, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x2c, 0x16, 0x49, 0x3e, 0x93, 0x02, 0x00, 0x00,
}
